version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 597345104684
    AWS_REGION: "us-east-1"
    REACT_APP_API_SERVICE_URL: "flask-react-alb-1125145780.us-east-1.elb.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building dev images...
      - docker-compose up -d --build
      - echo building prod images...
      - >
        docker build \
          -f be/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be \
          ./be
      - >
        docker build \
          -f fe/Dockerfile \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe \
          --build-arg NODE_ENV=production \
          ./fe
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-be
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/twtr-fe
